"""Long-term memory stored as Markdown files under data/memory/.

Layout:
- preferences.md  one dated entry per line:  ``- [YYYY-MM-DD] content``
- paths.md        grouped by task type under ``## {task_type}`` sections
- MEMORY.md       index regenerated by ``rebuild_index`` (for humans / UI)

All read/write paths are guarded by a module-level lock: only one turn runs
at a time per conversation, but multiple conversations may finish together.
"""
from __future__ import annotations

import re
import threading
from datetime import date as _date
from pathlib import Path
from typing import Dict, List, Optional, Union

_ENTRY_RE = re.compile(r"^- \[([0-9{\-}]+)\]\s*(.+)$")
_SECTION_RE = re.compile(r"^##\s*(.+)$")

KIND_PREFERENCE = "preference"
KIND_PATH = "path"
FILE_PREFERENCES = "preferences"
FILE_PATHS = "paths"

_lock = threading.Lock()


def _today() -> str:
    return _date.today().isoformat()


class MemoryStore:
    def __init__(self, base_dir: Union[str, Path]):
        self.base_dir = Path(base_dir)

    # ------------------------------------------------------------------
    # File helpers
    # ------------------------------------------------------------------

    @property
    def preferences_path(self) -> Path:
        return self.base_dir / "preferences.md"

    @property
    def paths_path(self) -> Path:
        return self.base_dir / "paths.md"

    @property
    def index_path(self) -> Path:
        return self.base_dir / "MEMORY.md"

    def ensure_files(self) -> None:
        with _lock:
            self._ensure_files_unlocked()

    def _ensure_files_unlocked(self) -> None:
        self.base_dir.mkdir(parents=True, exist_ok=True)
        for path in (self.preferences_path, self.paths_path, self.index_path):
            path.touch(exist_ok=True)

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def preferences(self) -> List[str]:
        with _lock:
            return self._read_preferences()

    def _read_preferences(self) -> List[str]:
        # Reads never create files: a missing store reads as empty so that
        # importing the app (or running tests) cannot pollute data/memory.
        if not self.preferences_path.exists():
            return []
        entries: List[str] = []
        for line in self.preferences_path.read_text(encoding="utf-8").splitlines():
            m = _ENTRY_RE.match(line.strip())
            if m:
                entries.append(m.group(2).strip())
        return entries

    def paths(self) -> Dict[str, List[str]]:
        with _lock:
            return self._read_paths()

    def _read_paths(self) -> Dict[str, List[str]]:
        if not self.paths_path.exists():
            return {}
        sections: Dict[str, List[str]] = {}
        current: Optional[str] = None
        for line in self.paths_path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            sec = _SECTION_RE.match(stripped)
            if sec:
                current = sec.group(1).strip()
                sections.setdefault(current, [])
                continue
            m = _ENTRY_RE.match(stripped)
            if m and current is not None:
                sections[current].append(m.group(2).strip())
        return sections

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def add(self, kind: str, content: str, task_type: str = "",
            date: Optional[str] = None) -> None:
        content = (content or "").strip()
        if not content:
            return
        dated = f"- [{date or _today()}] {content}"
        with _lock:
            self._ensure_files_unlocked()
            if kind == KIND_PREFERENCE:
                self._upsert_line(self.preferences_path, content, dated)
            elif kind == KIND_PATH:
                self._upsert_path_entry(task_type or "其他", content, dated)
            self._rebuild_index_unlocked()

    def _upsert_line(self, path: Path, content: str, dated: str) -> None:
        """Append an entry, or refresh the date if the same content exists."""
        lines = path.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            m = _ENTRY_RE.match(line.strip())
            if m and m.group(2).strip() == content:
                lines[i] = dated
                path.write_text("\n".join(lines) + "\n", encoding="utf-8")
                return
        lines.append(dated)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def _upsert_path_entry(self, task_type: str, content: str, dated: str) -> None:
        lines = self.paths_path.read_text(encoding="utf-8").splitlines()
        section_idx: Dict[str, int] = {}
        current: Optional[str] = None
        for i, line in enumerate(lines):
            sec = _SECTION_RE.match(line.strip())
            if sec:
                current = sec.group(1).strip()
                section_idx[current] = i
                continue
            m = _ENTRY_RE.match(line.strip())
            if m and current is not None and m.group(2).strip() == content:
                lines[i] = dated  # same content: refresh date in place
                self.paths_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
                return
        if task_type in section_idx:
            insert_at = self._section_end(lines, section_idx[task_type])
            lines.insert(insert_at, dated)
        else:
            if lines and lines[-1].strip():
                lines.append("")
            lines.append(f"## {task_type}")
            lines.append(dated)
        self.paths_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    @staticmethod
    def _section_end(lines: List[str], header_idx: int) -> int:
        end = len(lines)
        for i in range(header_idx + 1, len(lines)):
            if _SECTION_RE.match(lines[i].strip()):
                end = i
                break
        return end

    def update(self, match: str, content: str) -> bool:
        """Replace the entry whose full text equals ``match`` with ``content``."""
        match = (match or "").strip()
        content = (content or "").strip()
        if not match or not content:
            return False
        with _lock:
            self._ensure_files_unlocked()
            today = _today()
            hit = self._replace_in_file(self.preferences_path, match, content, today)
            if not hit:
                hit = self._replace_in_file(self.paths_path, match, content, today)
            if hit:
                self._rebuild_index_unlocked()
            return hit

    @staticmethod
    def _replace_in_file(path: Path, match: str, content: str, dated_prefix_day: str) -> bool:
        lines = path.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            m = _ENTRY_RE.match(line.strip())
            if m and m.group(2).strip() == match:
                lines[i] = f"- [{dated_prefix_day}] {content}"
                path.write_text("\n".join(lines) + "\n", encoding="utf-8")
                return True
        return False

    def delete(self, file: str, index: int) -> bool:
        with _lock:
            self._ensure_files_unlocked()
            path = self.preferences_path if file == FILE_PREFERENCES else self.paths_path
            lines = path.read_text(encoding="utf-8").splitlines()
            seen = 0
            for i, line in enumerate(lines):
                if _ENTRY_RE.match(line.strip()):
                    if seen == index:
                        del lines[i]
                        # drop a section header left without entries
                        if (i > 0 and _SECTION_RE.match(lines[i - 1].strip())
                                and (i >= len(lines) or not _ENTRY_RE.match(lines[i].strip()))
                                and (i + 1 >= len(lines) or not _ENTRY_RE.match(lines[i + 1].strip()))):
                            del lines[i - 1]
                        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
                        self._rebuild_index_unlocked()
                        return True
                    seen += 1
            return False

    def clear(self) -> None:
        with _lock:
            self._ensure_files_unlocked()
            self.preferences_path.write_text("", encoding="utf-8")
            self.paths_path.write_text("", encoding="utf-8")
            self._rebuild_index_unlocked()

    # ------------------------------------------------------------------
    # Index & ops
    # ------------------------------------------------------------------

    def rebuild_index(self) -> None:
        with _lock:
            self._ensure_files_unlocked()
            self._rebuild_index_unlocked()

    def _rebuild_index_unlocked(self) -> None:
        prefs = self._read_preferences()
        paths = self._read_paths()
        parts = ["# Memory Index", ""]
        parts.append("## Preferences")
        if prefs:
            parts.extend(f"- {p}" for p in prefs)
        else:
            parts.append("- (空)")
        parts.append("")
        parts.append("## Paths")
        if paths:
            for task_type, entries in paths.items():
                parts.append(f"### {task_type}")
                parts.extend(f"- {e}" for e in entries)
        else:
            parts.append("- (空)")
        self.index_path.write_text("\n".join(parts) + "\n", encoding="utf-8")

    def apply(self, ops: List[dict]) -> None:
        """Execute extractor ops: add / update (README §3.1 op structure)."""
        for op in ops or []:
            if not isinstance(op, dict):
                continue
            kind = op.get("op")
            if kind == "add":
                self.add(op.get("kind", KIND_PREFERENCE), op.get("content", ""),
                         task_type=op.get("task_type", "") or "")
            elif kind == "update":
                self.update(op.get("match", ""), op.get("content", ""))


_store: Optional[MemoryStore] = None


def get_store() -> MemoryStore:
    global _store
    if _store is None:
        _store = MemoryStore(Path("data") / "memory")
    return _store
